### PR TITLE
Added EWF Image Support using libewf and pytsk3

### PR DESCRIPTION
**Pull request by chapinb**
Great presentation and tool for the Google Analytics Cookies! 

I remember that you had mentioned that it did not currently support EWF images. Using [libewf from Joachim Metz](https://code.google.com/p/libewf/wiki/pyewf), I was able to hand the data from the E01 images into the rest of the script as a raw image. 

I have tested and verified the data with single and split E01 files and tested and verified again with a raw image to ensure I didn't break anything in the steps.

### CODE REVIEW

**Comment by mdegrazia** [comment]
This is great! I will review the code and get it merged. Quick question - will this require the user to have the libewf already, or install it before using the script?

**Comment by chapinb** [comment]
Yes it would. If they are running SIFT3 it should be installed, but let me take a look at it tomorrow and see if I can set it up so that the EWF option is only present if python is able to import the two needed libraries (pyewf and pytsk3).

**Comment by mdegrazia** [comment]
Thanks. Either way, I can just make sure to update the documentation so that the user is aware of this. For users that want to use it on Windows, I should be able to make an .exe that will include the libraries   so they won't have to worry about it.

**Comment by chapinb** [comment]
I made the changes as mentioned! If python cannot import those two libraries, then it removes the option for ewf and the other code further in the script. Let me know if there are any other changes to be made!

**Pull request merged**
